headerImage: /assets/img/uploads/img_3761-2-.jpg
contactMail: kontakt@team-buedesheim.blog
teaserText: >
  An der diesjährigen UNICON 21 - Unicycling Worldchampionships 2024 in Bemidji,
  Minnesota, USA nehmen fünf SportlerInnen aus Büdesheim teil. Über unsere
  sportlichen Leistungen und Erlebnisse wollen wir Euch in diesem Blog auf dem
  Laufenden halten.
sponsors:
  - name: Augenoptik Kerschbaumer
    logo: /assets/img/uploads/kerschbaumer-augenoptik-logo-adressen-komplett-farbig.png
    url: https://team-buedesheim.blog/
  - name: EAM
    logo: /assets/img/uploads/rz-eam-logo-3d.jpg
    url: https://team-buedesheim.blog/
