headerImage: assets/img/uploads/TZ6_9568.jpg
contactMail: "kontakt@team-buedesheim.blog"
teaserText: |
  An der diesjährigen UNICON 21 - Unicycling Worldchampionships 2024 in Bemidji, Minnesota, USA nehmen sechs SportlerInnen aus Büdesheim teil. Über unsere sportlichen Leistungen und Erlebnisse wollen wir Euch in diesem Blog auf dem Laufenden halten.
